apiVersion: v1
kind: Pod
metadata:
  name: psql-pod
  namespace: default  
spec:
  containers:
    - name: psql
      image: postgres:14.1
      env:
      - name: POSTGRES_PASSWORD
        value: pgpwd